# Generated by Django 4.2.4 on 2024-05-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentSystem', '0003_ocbureauleaderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCPresidentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocpresidentusername', models.CharField(max_length=100)),
                ('ocpresidentpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
