# Generated by Django 4.2.4 on 2024-05-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentSystem', '0005_oceventdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCEventData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OCEventName', models.CharField(max_length=200)),
                ('OCEventDescription', models.TextField()),
                ('OCEventLocation', models.CharField(max_length=200)),
                ('OCStartDate', models.DateField()),
                ('OCStartTime', models.TimeField()),
                ('OCEndDate', models.DateField()),
                ('OCEndTime', models.TimeField()),
                ('OCNeeded', models.IntegerField()),
            ],
        ),
    ]
