# Generated by Django 4.2.4 on 2024-06-04 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentSystem', '0006_oceventdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitmentSystem.oceventdata2')),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitmentSystem.ocdata')),
            ],
        ),
    ]
